# Generated by Django 4.1.3 on 2023-01-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
                ('rango_precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=40)),
                ('tiempo_de_entrega', models.IntegerField()),
                ('calificacion', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Pago',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='comision',
            new_name='cuotas',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='nombre',
            new_name='tipo_tarjeta',
        ),
    ]
